#ifndef SPECTRUMANALYSER_GLOBAL_H
#define SPECTRUMANALYSER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SPECTRUMANALYSER_LIBRARY)
#  define SPECTRUMANALYSERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SPECTRUMANALYSERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SPECTRUMANALYSER_GLOBAL_H
